FROM node:14-buster-slim as builder

COPY . /app

WORKDIR /app

ARG REACT_APP_API_URL
ARG REACT_APP_WS_URL

RUN yarn install || true
RUN yarn run build

FROM nginx:alpine

COPY --from=builder /app/build /usr/share/nginx/html
COPY config/nginx.conf /etc/nginx/conf.d/default.conf
#COPY config/nginx-snippets /etc/nginx/snippets

EXPOSE 80
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
