version: "3"
services:
  strapi:
    image: registry.gitlab.com/digitallforyou/skapa/preprod/strapi:preprod
    restart: always
    labels:
      traefik.frontend.rule: Host:strapi-skapa.hairun-technology.com
      traefik.enable: true
      traefik.port: 1337
      traefik.frontend.entryPoints: https,http,ws,wss
      traefik.frontend.redirect.entryPoint: https
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - traefik

  web:
    image: registry.gitlab.com/digitallforyou/skapa/preprod/web:preprod
    restart: always
    labels:
      traefik.frontend.rule: Host:skapa.hairun-technology.com
      traefik.enable: true
      traefik.port: 80
      traefik.frontend.entryPoints: https,http
      traefik.frontend.redirect.entryPoint: https
    env_file:
      - .env
    depends_on:
      - strapi
    networks:
      - traefik

  postgres:
    image: postgres:12
    restart: always
    labels:
      traefik.enable: false
    env_file:
      - .env
    volumes:
      - ./data/postgres/:/var/lib/postgresql
    ports:
      - 5444:5432
    networks:
      - traefik

  pgadmin:
    image: dpage/pgadmin4:4
    restart: always
    user: root
    env_file:
      - .env
    labels:
      traefik.frontend.rule: Host:pgadmin-skapa.hairun-technology.com
      traefik.enable: true
      traefik.port: 80
      traefik.frontend.entryPoints: https,http
      traefik.frontend.redirect.entryPoint: https
    depends_on:
      - postgres
    networks:
      - traefik

networks:
  traefik:
    external:
      name: skapa_preprod
