version: "3.6"
services:
  postgres:
    image: postgres:12
    restart: always
    labels:
      traefik.enable: false
    env_file:
      - .env-db
    volumes:
      - ./data/postgres/:/var/lib/postgresql
    ports:
      - '5432:5432'
#    networks:
#      - funow

  pgadmin:
    image: dpage/pgadmin4:4
    env_file:
      - .env-db
    ports:
      - "3005:80"
#    networks:
#      - funow

#networks:
#  funow:
#    external:
#      name: funow-dev
